info:
  contact: {}
paths:
  /Order:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get Order list
      tags:
      - Order
  /Order/{order_id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Order ID
        in: path
        name: order_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete Order by ID
      tags:
      - Order
    get:
      consumes:
      - application/json
      parameters:
      - description: Order ID
        in: path
        name: order_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get Order by ID
      tags:
      - Order
swagger: "2.0"
